import pathlib, shutil, json
run=pathlib.Path(__file__).resolve().parent
src=run/'worktrees'/'cinematic'; dst=run/'worktrees'/'final'
for name in ['kalman','secret/index.html','tests/secret-projects.test.cjs','tests/kalman.test.cjs','README.md']:
    source=src/name;target=dst/name
    if source.is_dir():shutil.copytree(source,target,dirs_exist_ok=True)
    else:target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(source,target)
shutil.copy2(run/'COMPARISON.md',dst/'.design-input'/'COMPARISON.md')
goal='''Follow AGENTS.md and frozen PROJECT_BRIEF/EVALUATION/COMPARISON in .design-input. Final worktree already contains the reviewed cinematic foundation. Integrate the specific compatible improvements below, keeping one coherent design and its tested core. Do not create a new alternative or change rivals.
1. Add aria-valuetext to logarithmic R/q sliders with actual physical variance and units on every update. Outputs explicitly aria-live=off. Add paused scrubber with seconds-valuetext/readout and To end control above scene; all44px. Tuning still pauses/rewinds same recorded data, world changes regenerate/clear baseline. Scrub updates summary/playback states without running.
2. Add Match actual noise, setting exact R=sensorSigma squared and q=accelSigma squared including zero q; preserve same data and baseline. Use a robust explicit mapping rather than rounding exact matches away. Nominal help must honestly indicate matching/mismatching current settings.
3. Borrow plain-language novice wording from clarity and learner question/feedback from workbench (adapt ideas, not whole conflicting implementations). Direct follow-one-correction anchor near intro/controls. Collapse optional equations/model details to reduce phone scroll. Keep numerical worked example and core teaching available. Learner prompt should use genuine dropout behavior and answer feedback.
4. Fit plot bounds to all displayed truth,fix,estimate,dead,baseline traces and uncertainty bounds. Guard invalid covariance noise parameters in numerical core (finite nonnegative q and finite positive R, valid noise/seed configs) with meaningful tests, preserving fixture/default seeded data. Keep actual world simulation separate from estimator.
5. No-JS fallback must work via script-disabled sandbox fixture if browser supports; controls unavailable before initialization. Preview default8314. Preserve existing projects. Save DELIVERY.md and actual evidence, run full tests and fresh desktop1440x900/phone390x844/320x740 browser checks. Verify each added feature, scenario endpoints, dropout growth, same-data gain response/baseline, keyboard, finite/reset, plot sizing and no console errors. Do not invent OS preference/screen-reader/benchmark checks; inspect reduced-motion CSS and record limitations. Keep checks appropriate, not endless polish. Complete when mandatory implemented journey checks pass; report unknown manual accessibility checks honestly.
Use native persisted Goal; follow max3 role cycles in AGENTS.md. No publishing or blanket commits. Do not edit original workspace outside final. Browser skill/tools if available. Deliver concrete finished files and evidence, not plans.'''
(dst/'.design-input'/'GOAL.md').write_text(goal,encoding='utf-8')
jobs={'jobs':[{'name':'final','cwd':str(dst),'objective':'Integrate and freshly validate the final Abyss robotics Kalman lab according to .design-input/GOAL.md and COMPARISON.md, following AGENTS.md. Deliver completed ready-to-use implementation and DELIVERY.md.','prompt':'Read .design-input/GOAL.md and execute the concrete integration on the existing cinematic foundation. All edits only inside this final worktree.','sandbox':'workspace-write'}]}
(run/'final-jobs.json').write_text(json.dumps(jobs,indent=2),encoding='utf-8')
